apiVersion: v1
kind: Secret
metadata: 
  name: my-db-secret
type: Opaque
data: 
  # values must be base64-encoded 
  DB_USER: YWRtaW4= # echo -n admin | base64
  DB_PWD: MWYyZDhjNDI= # echo -n 1f2d8c42 | base64
